<!DOCTYPE html>
<html>
	<head>
		<!-- meta tags -->
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
		
		<!-- site title -->
		<title><?php print $this->viewBag("title"); ?></title>
		
		<!-- icon links -->
		<link rel="shortcut icon" href="/Content/images/favicon.ico" type="image/x-icon" />
		
		<!-- get bootstrap css, font-awesome, and open sans font -->
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" />
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
		
		<?php $this->RenderSection("styles"); ?>

	</head>
	<body>
		<!-- render the body content -->
		<?php $this->RenderBody(); ?>

		<!-- render any page scripts -->
		<?php $this->RenderSection("scripts"); ?>
	</body>
</html>